### ISSUE TITLE
vcaca-ubuntu1804-analytics-dev image build failed on FFMPEG

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#533]
**The issue is found in master, introduced by PR #526** 
**Failure log:** 

In file included from /usr/local/include/opencv4/opencv2/core/core_c.h:48:0,
                 from libavfilter/vf_ocv_overlay.c:32:
/usr/local/include/opencv4/opencv2/core/types_c.h:367:20: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 CV_INLINE IplImage cvIplImage()
                    ^~~~~~~~~~
/usr/local/include/opencv4/opencv2/core/types_c.h:717:19: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 CV_INLINE CvMatND cvMatND()
                   ^~~~~~~
libavfilter/vf_ocv_overlay.c:40:10: fatal error: json-c/json.h: No such file or directory
 #include <json-c/json.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [libavfilter/vf_ocv_overlay.o] Error 1
ffbuild/common.mak:59: recipe for target 'libavfilter/vf_ocv_overlay.o' failed
make: *** Waiting for unfinished jobs....
CC      libavfilter/vf_owdenoise.o
The command '/bin/bash -o pipefail -c cd /home/FFmpeg &&     export PKG_CONFIG_PATH="/usr/local/lib/x86_64-linux-gnu/pkgconfig" &&     ./configure --prefix="/openvino/deployment_tools/inference_engine/lib/intel64 " --libdir=/usr/local/lib/x86_64-linux-gnu --extra-libs="-lpthread -lm" --enable-shared --enable-gpl bvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libinference_engine_c_api --enable-librdkafka --enable-libopencv  &&     make -j8 &&     ma
VCAC-A/ubuntu-18.04/analytics/dev/CMakeFiles/build_vcaca_analytics_devel_ubuntu1804.dir/build.make:57: recipe for target 'VCAC-A/ubuntu-18.04/analytics/dev/C
make[2]: *** [VCAC-A/ubuntu-18.04/analytics/dev/CMakeFiles/build_vcaca_analytics_devel_ubuntu1804] Error 2
CMakeFiles/Makefile2:26978: recipe for target 'VCAC-A/ubuntu-18.04/analytics/dev/CMakeFiles/build_vcaca_analytics_devel_ubuntu1804.dir/all' failed
make[1]: *** [VCAC-A/ubuntu-18.04/analytics/dev/CMakeFiles/build_vcaca_analytics_devel_ubuntu1804.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhou5** [comment]
Fixed. #534

**Comment by jhou5** [comment]
Same issue found in ubuntu1604 OS
